#! /bin/sh
# postrm script for hddtemp
set -e

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d caliper remove >/dev/null || exit 0
fi
# End automatically added section


exit 0
