#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/caliper" ]; then
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d caliper stop || exit 0
	else
		/etc/init.d/caliper stop || exit 0
	fi
fi
# End automatically added section
